INSERT INTO genre (name, description)
VALUES ("rock", "is a broad genre of popular music that originated as 'rock and roll' in the United States in the early 1950s, and developed into a range of different styles in the 1960s and later, particularly in the United States and the United Kingdom. It has its roots in 1940s and 1950s rock and roll, a style which drew heavily from the genres of blues, rhythm and blues, and from country music. Rock music also drew strongly from a number of other genres such as electric blues and folk, and incorporated influences from jazz, classical and other musical styles. Musically, rock has centered on the electric guitar, usually as part of a rock group with electric bass, drums, and one or more singers. Usually, rock is song-based music with a 4/4 time signature using a verse–chorus form, but the genre has become extremely diverse. Like pop music, lyrics often stress romantic love but also address a wide variety of other themes that are frequently social or political.");
INSERT INTO genre (name, description)
VALUES ("country", "Country music, also known as country and western, and hillbilly music, is a genre of popular music that originated in the Southern United States in the early 1920s. It takes its roots from genres such as American folk music and blues.
The first generation emerged in the early 1920s, with Atlanta's music scene playing a major role in launching country's earliest recording artists. James Gideon Tanner was an American old-time fiddler and one of the earliest stars of what would come to be known as country music. His band, the Skillet Lickers, was one of the most innovative and influential string bands of the 1920s and 1930s. Its most notable members were Clayton McMichen, Dan Hornsby, Riley Puckett and Robert Lee Sweat. New York City record label Okeh Records began issuing hillbilly music records by Fiddlin' John Carson as early as 1923, followed by Columbia Records in 1924, and RCA Victor Records in 1927 with the first famous pioneers of the genre Jimmie Rodgers and the first family of country music The Carter Family. Many 'hillbilly' musicians, such as Cliff Carlisle, recorded blues songs throughout the 1920s.");
INSERT INTO genre (name, description)
VALUES ("blues", "Blues is a music genre and musical form which was originated in the Deep South of the United States around the 1870s by African-Americans from roots in African musical traditions, African-American work songs, and spirituals. Blues incorporated spirituals, work songs, field hollers, shouts, chants, and rhymed simple narrative ballads. The blues form, ubiquitous in jazz, rhythm and blues and rock and roll, is characterized by the call-and-response pattern, the blues scale and specific chord progressions, of which the twelve-bar blues is the most common. Blue notes (or 'worried notes'), usually thirds, fifths or sevenths flattened in pitch are also an essential part of the sound. Blues shuffles or walking bass reinforce the trance-like rhythm and form a repetitive effect known as the groove.");
INSERT INTO genre (name, description)
VALUES ("reggae", "Reggae is a music genre that originated in Jamaica in the late 1960s. The term also denotes the modern popular music of Jamaica and its diaspora. A 1968 single by Toots and the Maytals, 'Do the Reggay' was the first popular song to use the word 'reggae', effectively naming the genre and introducing it to a global audience. While sometimes used in a broad sense to refer to most types of popular Jamaican dance music, the term reggae more properly denotes a particular music style that was strongly influenced by traditional mento as well as American jazz and rhythm and blues, especially the New Orleans R&B practiced by Fats Domino and Allen Toussaint, and evolved out of the earlier genres ska and rocksteady. Reggae usually relates news, social gossip, and political commentary. Reggae spread into a commercialized jazz field, being known first as 'rudie blues', then 'ska', later 'blue beat', and 'rock steady'. It is instantly recognizable from the counterpoint between the bass and drum downbeat and the offbeat rhythm section. The immediate origins of reggae were in ska and rocksteady; from the latter, reggae took over the use of the bass as a percussion instrument.");
INSERT INTO genre (name, description)
VALUES ("metal", "Metal or Heavy Metal is a genre of rock music that developed in the late 1960s and early 1970s, largely in the United Kingdom and the United States. With roots in blues rock, psychedelic rock, and acid rock, the bands that created heavy metal developed a thick, massive sound, characterized by highly amplified distortion, extended guitar solos, emphatic beats, and overall loudness. The genre's lyrics and performance styles are sometimes associated with aggression and machismo.");


INSERT INTO genre (name, description)
VALUES ("jazz", "Jazz is a music genre that originated in the African-American communities of New Orleans, United States. It originated in the late 19th and early 20th centuries, and developed from roots in blues and ragtime. Jazz is seen by many as (America's classical music). Since the 1920s Jazz Age, jazz has become recognized as a major form of musical expression. It then emerged in the form of independent traditional and popular musical styles, all linked by the common bonds of African-American and European-American musical parentage with a performance orientation. Jazz is characterized by swing and blue notes, call and response vocals, polyrhythms and improvisation. Jazz has roots in West African cultural and musical expression, and in African-American music traditions including blues and ragtime, as well as European military band music. Intellectuals around the world have hailed jazz as (one of America's original art forms).");
INSERT INTO genre (name, description)
VALUES ("punk", "Punk rock (or simply punk) is a music genre that emerged in the mid-1970s. Rooted in 1960s garage rock, punk bands rejected the perceived excesses of mainstream 1970s rock. They typically produced short, fast-paced songs with hard-edged melodies and singing styles, stripped-down instrumentation, and often political, anti-establishment lyrics. Punk embraces a DIY ethic; many bands self-produce recordings and distribute them through independent record labels.");
INSERT INTO genre (name, description)
VALUES ("hip hop", "Hip hop music, also called hip-hop or rap music, is a genre of popular music developed in the United States by inner-city African Americans and Latino Americans in the Bronx borough of New York City in the 1970s. It consists of a stylized rhythmic music that commonly accompanies rapping, a rhythmic and rhyming speech that is chanted. It developed as part of hip hop culture, a subculture defined by four key stylistic elements: MCing/rapping, DJing/scratching with turntables, break dancing, and graffiti writing. Other elements include sampling beats or bass lines from records (or synthesized beats and sounds), and rhythmic beatboxing. While often used to refer solely to rapping, 'hip hop' more properly denotes the practice of the entire subculture. The term hip hop music is sometimes used synonymously with the term rap music, though rapping is not a required component of hip hop music; the genre may also incorporate other elements of hip hop culture, including DJing, turntablism, scratching, beatboxing, and instrumental tracks.");
INSERT INTO genre (name, description)
VALUES ("rhytm & blues", "Rhythm and blues, commonly abbreviated as R&B, is a genre of popular music that originated in African American communities in the 1940s. The term was originally used by record companies to describe recordings marketed predominantly to urban African Americans, at a time when 'urbane, rocking, jazz based music with a heavy, insistent beat' was becoming more popular. In the commercial rhythm and blues music typical of the 1950s through the 1970s, the bands usually consisted of piano, one or two guitars, bass, drums, one or more saxophones, and sometimes background vocalists. R&B lyrical themes often encapsulate the African-American experience of pain and the quest for freedom and joy, as well as triumphs and failures in terms of relationships, economics, and aspirations.");
INSERT INTO genre (name, description)
VALUES ("house", "House is a genre of electronic dance music with a repetitive, 4/4 beat, usually with 120-130 beats per minute. It was created by disc jockeys and music producers from Chicago's underground club culture in the early and mid 1980s, as DJs from the subculture began altering disco dance tracks to give them a more mechanical beat and deeper basslines. As well, these DJs began to mix synth pop, rap, Latin music, and even jazz into their tracks.");

INSERT INTO genre (name, description)
VALUES ("classical", "Classical music is art music produced or rooted in the traditions of Western culture, including both liturgical (religious) and secular music. While a more precise term is also used to refer to the period from 1750 to 1820 (the Classical period), this article is about the broad span of time from before the 6th century AD to the present day, which includes the Classical period and various other periods. The central norms of this tradition became codified between 1550 and 1900, which is known as the common-practice period.");
INSERT INTO genre (name, description)
VALUES ("folk", "Folk music includes traditional folk music and the genre that evolved from it during the 20th-century folk revival. Some types of folk music may be called world music. Traditional folk music has been defined in several ways: as music transmitted orally, music with unknown composers, or music performed by custom over a long period of time. It has been contrasted with commercial and classical styles. The term originated in the 19th century, but folk music extends beyond that.");
INSERT INTO genre (name, description)
VALUES ("swing", "Swing music, or simply swing, is a form of popular jazz music developed in the United States that dominated in the 1930s and 1940s. The name swing came from the 'swing feel' where the emphasis is on the off–beat or weaker pulse in the music. Swing bands usually featured soloists who would improvise on the melody over the arrangement. The danceable swing style of big bands and bandleaders such as Benny Goodman was the dominant form of American popular music from 1935 to 1946, a period known as the swing era. The verb 'to swing' is also used as a term of praise for playing that has a strong groove or drive. Notable musicians of the swing era include Louis Armstrong, Count Basie, Cab Calloway, Jimmy Dorsey, Tommy Dorsey, Duke Ellington, Benny Goodman, Woody Herman, Harry James, Louis Jordan, Glenn Miller, Louis Prima, and Artie Shaw.");
INSERT INTO genre (name, description)
VALUES ("emo", "Emo is a rock music genre characterized by an emphasis on emotional expression, sometimes through confessional lyrics. It emerged as a style of post-hardcore from the mid-1980s hardcore punk movement in Washington, D.C., where it was known as emotional hardcore or emocore and pioneered by bands such as Rites of Spring and Embrace. In the early–mid 1990s, emo was adopted and reinvented by alternative rock, indie rock and pop punk bands such as Sunny Day Real Estate, Jawbreaker, Weezer and Jimmy Eat World, with Weezer breaking into the mainstream during this time. By the mid-1990s, bands such as Braid, the Promise Ring and the Get Up Kids emerged from the burgeoning Midwest emo scene, and several independent record labels began to specialize in the genre. Meanwhile, screamo, a more aggressive style of emo using screamed vocals, also emerged, pioneered by the San Diego bands Heroin and Antioch Arrow. Screamo achieved mainstream success in the 2000s with bands like Hawthorne Heights, Silverstein, Story of the Year, Thursday, The Used, and Underoath.");
INSERT INTO genre (name, description)
VALUES ("pop", "Pop music is a genre of popular music that originated in its modern forms in the US and the UK during the mid-1950s. The terms 'popular music' and 'pop music' are often used interchangeably, although both describe all music that is popular and that include many diverse styles. 'Pop' and 'rock' were roughly synonymous terms until the late 1960s, when they became quite separated from each other. Although much of the music that appears on record charts is seen as pop music, the genre is distinguished from chart music. Pop music often borrows elements from other styles such as urban, dance, rock, Latin, and country; nevertheless, there are many key elements that define pop music. Identifying factors usually include short to medium-length songs written in a basic format (often the verse-chorus structure), as well as common use of repeated choruses, melodic tunes, and hooks.");


INSERT INTO comment (commenterName, text, mediaLink)
VALUES ("Captain Falcon", "My favorite kind of music!", "https://www.youtube.com/results?search_query=rock");

SELECT * FROM genre;
SELECT * FROM comment;